package com.minepacu.craftpresence.ui.localization

import android.os.LocaleList
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalConfiguration
import com.minepacu.craftpresence.core.config.AppLanguage
import java.util.Locale

val LocalizedTextProvider = staticCompositionLocalOf { EnglishText }

@Immutable
data class LocalizedText(
    val tabOverview: String,
    val tabDiscord: String,
    val tabPrograms: String,
    val tabPresence: String,
    val tabMusic: String,
    val tabPermissions: String,
    val tabSettings: String,
    val headerSubtitle: String,
    val discordAutoConnectFailed: String,
    val discordAutoConnect: String,
    val foregroundAppTitle: String,
    val noDetectedApp: String,
    val usageAccessMayBeRequired: String,
    val tracked: String,
    val untracked: String,
    val discordConnect: String,
    val discordOnboardingBody: String,
    val status: String,
    val notConfiguredValue: String,
    val discordAuthStart: String,
    val discordAccountConnected: String,
    val discordConnectFailed: String,
    val connectAccount: String,
    val later: String,
    val noConnectedAccount: String,
    val registeredApps: String,
    val appDetectionRunning: String,
    val appDetectionStopped: String,
    val currentApp: String,
    val unknown: String,
    val displayOff: String,
    val noUsageInfo: String,
    val canEnableInSettings: String,
    val music: String,
    val active: String,
    val standby: String,
    val noPlaybackInfo: String,
    val currentDetectionInfo: String,
    val display: String,
    val on: String,
    val off: String,
    val appName: String,
    val hidden: String,
    val packageName: String,
    val registrationStatus: String,
    val discordStatus: String,
    val lastError: String,
    val authorization: String,
    val account: String,
    val none: String,
    val userId: String,
    val actions: String,
    val reconnect: String,
    val connect: String,
    val accountRefreshSuccess: String,
    val accountRefreshFailed: String,
    val refreshAccount: String,
    val discordDisconnected: String,
    val disconnect: String,
    val requirements: String,
    val discordRequirementInstalled: String,
    val discordRequirementApplicationId: String,
    val discordRequirementRichPresence: String,
    val applicationIdNeedsCheck: String,
    val appRichPresence: String,
    val presenceCustomizer: String,
    val presenceCustomizerDescription: String,
    val currentPresence: String,
    val refreshPresence: String,
    val noRegisteredAppsForPresence: String,
    val selectPresenceApp: String,
    val presenceReloaded: String,
    val operation: String,
    val running: String,
    val stopped: String,
    val notDetected: String,
    val startDetection: String,
    val stop: String,
    val appToRegister: String,
    val appRegistrationDescription: String,
    val displayName: String,
    val displayNameExample: String,
    val chooseInstalledApp: String,
    val installedApps: String,
    val searchApps: String,
    val showSystemApps: String,
    val systemApp: String,
    val noAppsFound: String,
    val selectApp: String,
    val alreadyRegistered: String,
    val addManually: String,
    val addCurrentApp: String,
    val addAppleMusic: String,
    val enableForegroundHint: String,
    val currentDetected: String,
    val presenceSettings: String,
    val delete: String,
    val activityType: String,
    val detailText: String,
    val defaultDetailText: String,
    val stateText: String,
    val defaultStateText: String,
    val templateHelp: String,
    val useAppIconForLargeImage: String,
    val largeImageKeyOrUrl: String,
    val discordAssetKeyOrUrl: String,
    val largeImageText: String,
    val imageHoverText: String,
    val smallImageKeyOrUrl: String,
    val smallImageText: String,
    val partyCurrent: String,
    val partyMax: String,
    val save: String,
    val cancel: String,
    val playbackStatus: String,
    val playing: String,
    val track: String,
    val artist: String,
    val album: String,
    val albumImage: String,
    val startMusicPresence: String,
    val musicPlatforms: String,
    val enabledPlatforms: String,
    val startAllMusicPlatforms: String,
    val stopAll: String,
    val enable: String,
    val howItWorks: String,
    val mediaSessionDescription: String,
    val artworkLookupDescription: String,
    val discordMusicDescription: String,
    val usageAccess: String,
    val usageAccessDescription: String,
    val notificationAccess: String,
    val notificationAccessDescription: String,
    val refreshPermissionStatus: String,
    val granted: String,
    val required: String,
    val settingsRequired: String,
    val openSettings: String,
    val appSettings: String,
    val showForegroundApp: String,
    val showForegroundAppDescription: String,
    val showForegroundAppNotification: String,
    val showForegroundAppNotificationDescription: String,
    val notificationPermissionMissing: String,
    val appNotificationPermission: String,
    val appNotificationPermissionDescription: String,
    val discordAutoConnectDescriptionOn: String,
    val discordAutoConnectDescriptionOff: String,
    val language: String,
    val registeredPackages: String,
    val customPresenceSettings: String,
    val configured: String,
    val authorizing: String,
    val connecting: String,
    val ready: String,
    val unauthorized: String,
    val failed: String,
    val authorized: String,
    val playingActivity: String,
    val streamingActivity: String,
    val listeningActivity: String,
    val watchingActivity: String,
    val competingActivity: String,
    val languageSystem: String,
    val languageKorean: String,
    val languageEnglish: String,
    val languageJapanese: String,
) {
    fun countItems(count: Int): String = when (this) {
        KoreanText -> "${count}개"
        JapaneseText -> "${count}件"
        else -> "$count"
    }

    fun currentDetectedValue(value: String): String = when (this) {
        KoreanText -> "$currentDetected: $value"
        JapaneseText -> "$currentDetected: $value"
        else -> "$currentDetected: $value"
    }
}

@Composable
fun rememberLocalizedText(language: AppLanguage): LocalizedText {
    val configuration = LocalConfiguration.current
    return remember(language, configuration) {
        val systemLocale = configuration.locales.firstOrNullCompat() ?: Locale.getDefault()
        when (language) {
            AppLanguage.SYSTEM -> textFor(systemLocale.language)
            AppLanguage.KOREAN -> KoreanText
            AppLanguage.ENGLISH -> EnglishText
            AppLanguage.JAPANESE -> JapaneseText
        }
    }
}

private fun LocaleList.firstOrNullCompat(): Locale? = if (size() == 0) null else get(0)

private fun textFor(languageCode: String): LocalizedText = when (languageCode.lowercase(Locale.ROOT)) {
    "ko" -> KoreanText
    "ja" -> JapaneseText
    else -> EnglishText
}

val KoreanText = LocalizedText(
    tabOverview = "개요",
    tabDiscord = "Discord",
    tabPrograms = "앱",
    tabPresence = "Presence",
    tabMusic = "음악",
    tabPermissions = "권한",
    tabSettings = "설정",
    headerSubtitle = "Android에서 앱 사용 상태와 음악 재생 정보를 Discord Rich Presence로 보냅니다.",
    discordAutoConnectFailed = "Discord 자동 연결에 실패했습니다.",
    discordAutoConnect = "Discord 자동 연결",
    foregroundAppTitle = "현재 포그라운드 앱",
    noDetectedApp = "감지된 앱 없음",
    usageAccessMayBeRequired = "사용 정보 접근 권한이 필요할 수 있습니다.",
    tracked = "등록됨",
    untracked = "미등록",
    discordConnect = "Discord 연결",
    discordOnboardingBody = "처음 실행할 때 Discord 계정을 연결합니다. SDK 인증이 시작되면 Discord 앱 또는 웹 로그인 화면에서 계정 승인을 완료해야 합니다.",
    status = "상태",
    notConfiguredValue = "설정되지 않음",
    discordAuthStart = "Discord 인증을 시작합니다. Discord 앱 또는 웹 로그인 화면에서 승인을 완료해 주세요.",
    discordAccountConnected = "Discord 계정이 연결되었습니다.",
    discordConnectFailed = "Discord 연결에 실패했습니다.",
    connectAccount = "연결하기",
    later = "나중에",
    noConnectedAccount = "연결된 계정 없음",
    registeredApps = "등록 앱",
    appDetectionRunning = "앱 감지 실행 중",
    appDetectionStopped = "앱 감지 중지됨",
    currentApp = "현재 앱",
    unknown = "알 수 없음",
    displayOff = "표시 꺼짐",
    noUsageInfo = "사용 정보 없음",
    canEnableInSettings = "설정에서 다시 켤 수 있습니다.",
    music = "음악",
    active = "활성",
    standby = "대기",
    noPlaybackInfo = "재생 정보 없음",
    currentDetectionInfo = "현재 감지 정보",
    display = "표시",
    on = "켜짐",
    off = "꺼짐",
    appName = "앱 이름",
    hidden = "숨김",
    packageName = "패키지",
    registrationStatus = "등록 여부",
    discordStatus = "Discord 상태",
    lastError = "마지막 오류",
    authorization = "인증",
    account = "계정",
    none = "없음",
    userId = "사용자 ID",
    actions = "작업",
    reconnect = "다시 연결",
    connect = "연결",
    accountRefreshSuccess = "계정 정보를 새로 불러왔습니다.",
    accountRefreshFailed = "계정 정보를 불러오지 못했습니다.",
    refreshAccount = "계정 새로고침",
    discordDisconnected = "Discord 연결을 해제했습니다.",
    disconnect = "연결 해제",
    requirements = "필요 조건",
    discordRequirementInstalled = "Discord 앱 또는 브라우저 로그인 화면에서 Discord 계정 승인을 완료해야 합니다.",
    discordRequirementApplicationId = "Application ID는 AndroidManifest manifest placeholder로 주입됩니다.",
    discordRequirementRichPresence = "Rich Presence 갱신은 연결된 Discord 계정 권한을 사용합니다.",
    applicationIdNeedsCheck = "Application ID 확인 필요",
    appRichPresence = "앱 Rich Presence",
    presenceCustomizer = "Presence 커스터마이징",
    presenceCustomizerDescription = "등록된 앱의 현재 Presence 설정을 불러와 직접 수정합니다.",
    currentPresence = "현재 Presence",
    refreshPresence = "Presence 새로고침",
    noRegisteredAppsForPresence = "Presence를 수정하려면 먼저 앱 탭에서 앱을 등록하세요.",
    selectPresenceApp = "Presence를 수정할 앱",
    presenceReloaded = "저장된 Presence를 다시 불러왔습니다.",
    operation = "동작",
    running = "실행 중",
    stopped = "중지됨",
    notDetected = "감지 안 됨",
    startDetection = "감지 시작",
    stop = "중지",
    appToRegister = "등록할 앱",
    appRegistrationDescription = "패키지 이름과 표시 이름을 등록하면 해당 앱이 전면에 있을 때 Discord에 \"앱 이름 앱 사용 중\"으로 표시합니다.",
    displayName = "표시 이름",
    displayNameExample = "예: Chrome",
    chooseInstalledApp = "설치된 앱에서 선택",
    installedApps = "설치된 앱",
    searchApps = "앱 이름 또는 패키지 검색",
    showSystemApps = "시스템 앱 표시",
    systemApp = "시스템",
    noAppsFound = "검색 결과가 없습니다.",
    selectApp = "선택",
    alreadyRegistered = "등록됨",
    addManually = "직접 추가",
    addCurrentApp = "현재 앱 추가",
    addAppleMusic = "Apple Music 추가",
    enableForegroundHint = "현재 앱 추가 기능은 설정에서 포그라운드 앱 표시를 켜면 사용할 수 있습니다.",
    currentDetected = "현재 감지",
    presenceSettings = "Presence 설정",
    delete = "삭제",
    activityType = "활동 유형",
    detailText = "상세 문구",
    defaultDetailText = "{app} 앱 사용 중",
    stateText = "상태 문구",
    defaultStateText = "사용 중",
    templateHelp = "{app}, {package}, {title} 값을 문구 안에 사용할 수 있습니다.",
    useAppIconForLargeImage = "앱 아이콘을 큰 이미지로 사용",
    largeImageKeyOrUrl = "큰 이미지 키/URL",
    discordAssetKeyOrUrl = "Discord asset key 또는 URL",
    largeImageText = "큰 이미지 설명",
    imageHoverText = "이미지 hover 텍스트",
    smallImageKeyOrUrl = "작은 이미지 키/URL",
    smallImageText = "작은 이미지 설명",
    partyCurrent = "파티 현재 인원",
    partyMax = "파티 최대 인원",
    save = "저장",
    cancel = "취소",
    playbackStatus = "재생 상태",
    playing = "재생 중",
    track = "곡",
    artist = "아티스트",
    album = "앨범",
    albumImage = "앨범 이미지",
    startMusicPresence = "음악 Presence 시작",
    musicPlatforms = "음악 플랫폼",
    enabledPlatforms = "활성 플랫폼",
    startAllMusicPlatforms = "전체 시작",
    stopAll = "전체 중지",
    enable = "켜기",
    howItWorks = "동작 방식",
    mediaSessionDescription = "Android MediaSession에서 현재 재생 중인 트랙을 읽습니다.",
    artworkLookupDescription = "앨범 아트 URL이 없으면 iTunes Search API 조회 결과를 캐시해 사용합니다.",
    discordMusicDescription = "Discord에는 곡명, 아티스트, 재생 시작/종료 시간이 반영됩니다.",
    usageAccess = "사용 정보 접근",
    usageAccessDescription = "현재 전면 앱을 감지해 등록된 앱의 Presence를 갱신할 때 필요합니다.",
    notificationAccess = "알림 접근",
    notificationAccessDescription = "MediaSession의 현재 재생 정보를 안정적으로 읽을 때 필요합니다.",
    refreshPermissionStatus = "권한 상태 새로고침",
    granted = "허용됨",
    required = "필요함",
    settingsRequired = "설정 필요",
    openSettings = "설정 열기",
    appSettings = "앱 설정",
    showForegroundApp = "포그라운드 앱 표시",
    showForegroundAppDescription = "앱 상단에 현재 열려 있는 앱 이름과 패키지를 표시합니다.",
    showForegroundAppNotification = "포그라운드 앱 알림",
    showForegroundAppNotificationDescription = "현재 전면 앱을 Android 알림으로 계속 표시합니다.",
    notificationPermissionMissing = "알림 권한이 꺼져 있으면 표시되지 않습니다.",
    appNotificationPermission = "앱 알림",
    appNotificationPermissionDescription = "현재 포그라운드 앱을 알림으로 표시할 때 필요합니다.",
    discordAutoConnectDescriptionOn = "다음 실행부터 백그라운드에서 Discord 연결을 시도합니다.",
    discordAutoConnectDescriptionOff = "다음 실행 시 초기 연결 창을 표시합니다.",
    language = "언어",
    registeredPackages = "등록된 패키지",
    customPresenceSettings = "개별 Presence 설정",
    configured = "설정됨",
    authorizing = "인증 중",
    connecting = "연결 중",
    ready = "준비됨",
    unauthorized = "미인증",
    failed = "실패",
    authorized = "인증됨",
    playingActivity = "플레이",
    streamingActivity = "스트리밍",
    listeningActivity = "듣는 중",
    watchingActivity = "시청 중",
    competingActivity = "경쟁 중",
    languageSystem = "시스템",
    languageKorean = "한국어",
    languageEnglish = "English",
    languageJapanese = "日本語",
)

val EnglishText = KoreanText.copy(
    tabOverview = "Overview",
    tabPrograms = "Apps",
    tabPresence = "Presence",
    tabMusic = "Music",
    tabPermissions = "Permissions",
    tabSettings = "Settings",
    headerSubtitle = "Send app usage and music playback status from Android to Discord Rich Presence.",
    discordAutoConnectFailed = "Discord auto-connect failed.",
    discordAutoConnect = "Discord auto-connect",
    foregroundAppTitle = "Current foreground app",
    noDetectedApp = "No app detected",
    usageAccessMayBeRequired = "Usage access permission may be required.",
    tracked = "Registered",
    untracked = "Not registered",
    discordConnect = "Discord connection",
    discordOnboardingBody = "Connect your Discord account on first launch. When SDK authorization starts, finish account approval in the Discord app or web login screen.",
    status = "Status",
    notConfiguredValue = "Not configured",
    discordAuthStart = "Starting Discord authorization. Finish approval in the Discord app or web login screen.",
    discordAccountConnected = "Discord account connected.",
    discordConnectFailed = "Discord connection failed.",
    connectAccount = "Connect",
    later = "Later",
    noConnectedAccount = "No connected account",
    registeredApps = "Registered apps",
    appDetectionRunning = "App detection running",
    appDetectionStopped = "App detection stopped",
    currentApp = "Current app",
    unknown = "Unknown",
    displayOff = "Display off",
    noUsageInfo = "No usage info",
    canEnableInSettings = "You can enable it again in Settings.",
    music = "Music",
    active = "Active",
    standby = "Standby",
    noPlaybackInfo = "No playback info",
    currentDetectionInfo = "Current detection",
    display = "Display",
    on = "On",
    off = "Off",
    appName = "App name",
    hidden = "Hidden",
    registrationStatus = "Registration",
    discordStatus = "Discord status",
    lastError = "Last error",
    authorization = "Authorization",
    account = "Account",
    none = "None",
    userId = "User ID",
    actions = "Actions",
    reconnect = "Reconnect",
    connect = "Connect",
    accountRefreshSuccess = "Account information refreshed.",
    accountRefreshFailed = "Could not load account information.",
    refreshAccount = "Refresh account",
    discordDisconnected = "Disconnected from Discord.",
    disconnect = "Disconnect",
    requirements = "Requirements",
    discordRequirementInstalled = "Approve your Discord account in the Discord app or browser login screen.",
    discordRequirementApplicationId = "Application ID is injected through the AndroidManifest manifest placeholder.",
    discordRequirementRichPresence = "Rich Presence updates use the connected Discord account permissions.",
    applicationIdNeedsCheck = "Application ID needs review",
    appRichPresence = "App Rich Presence",
    presenceCustomizer = "Presence customization",
    presenceCustomizerDescription = "Load and edit the current Presence settings for registered apps.",
    currentPresence = "Current Presence",
    refreshPresence = "Refresh Presence",
    noRegisteredAppsForPresence = "Register an app in the Apps tab before editing Presence.",
    selectPresenceApp = "App to edit",
    presenceReloaded = "Reloaded saved Presence.",
    operation = "Operation",
    running = "Running",
    stopped = "Stopped",
    notDetected = "Not detected",
    startDetection = "Start detection",
    stop = "Stop",
    appToRegister = "App to register",
    appRegistrationDescription = "Register a package name and display name to show \"Using app name\" on Discord when that app is in front.",
    packageName = "Package name",
    displayName = "Display name",
    displayNameExample = "Example: Chrome",
    chooseInstalledApp = "Choose installed app",
    installedApps = "Installed apps",
    searchApps = "Search app name or package",
    showSystemApps = "Show system apps",
    systemApp = "System",
    noAppsFound = "No apps found.",
    selectApp = "Select",
    alreadyRegistered = "Registered",
    addManually = "Add manually",
    addCurrentApp = "Add current app",
    addAppleMusic = "Add Apple Music",
    enableForegroundHint = "Enable foreground app display in Settings to use Add current app.",
    currentDetected = "Current detection",
    presenceSettings = "Presence settings",
    delete = "Delete",
    activityType = "Activity type",
    detailText = "Details text",
    defaultDetailText = "Using {app}",
    stateText = "State text",
    defaultStateText = "In use",
    templateHelp = "You can use {app}, {package}, and {title} in the text.",
    useAppIconForLargeImage = "Use app icon as large image",
    largeImageKeyOrUrl = "Large image key/URL",
    discordAssetKeyOrUrl = "Discord asset key or URL",
    largeImageText = "Large image text",
    imageHoverText = "Image hover text",
    smallImageKeyOrUrl = "Small image key/URL",
    smallImageText = "Small image text",
    partyCurrent = "Party current size",
    partyMax = "Party max size",
    save = "Save",
    cancel = "Cancel",
    playbackStatus = "Playback status",
    playing = "Playing",
    track = "Track",
    artist = "Artist",
    album = "Album",
    albumImage = "Album image",
    startMusicPresence = "Start music Presence",
    musicPlatforms = "Music platforms",
    enabledPlatforms = "Enabled platforms",
    startAllMusicPlatforms = "Start all",
    stopAll = "Stop all",
    enable = "Enable",
    howItWorks = "How it works",
    mediaSessionDescription = "Reads the currently playing track from Android MediaSession.",
    artworkLookupDescription = "If album artwork URL is missing, caches results from the iTunes Search API.",
    discordMusicDescription = "Discord receives the track title, artist, and playback start/end time.",
    usageAccess = "Usage access",
    usageAccessDescription = "Required to detect the foreground app and update Presence for registered apps.",
    notificationAccess = "Notification access",
    notificationAccessDescription = "Required to reliably read current playback information from MediaSession.",
    refreshPermissionStatus = "Refresh permission status",
    granted = "Allowed",
    required = "Required",
    settingsRequired = "Settings required",
    openSettings = "Open settings",
    appSettings = "App settings",
    showForegroundApp = "Show foreground app",
    showForegroundAppDescription = "Shows the currently open app name and package at the top of the app.",
    showForegroundAppNotification = "Foreground app notification",
    showForegroundAppNotificationDescription = "Keeps the current foreground app visible in an Android notification.",
    notificationPermissionMissing = "It will not appear while notification permission is off.",
    appNotificationPermission = "App notifications",
    appNotificationPermissionDescription = "Required to show the current foreground app as a notification.",
    discordAutoConnectDescriptionOn = "The app will try to connect to Discord in the background from the next launch.",
    discordAutoConnectDescriptionOff = "The initial connection dialog will appear on the next launch.",
    language = "Language",
    registeredPackages = "Registered packages",
    customPresenceSettings = "Custom Presence settings",
    configured = "Configured",
    authorizing = "Authorizing",
    connecting = "Connecting",
    ready = "Ready",
    unauthorized = "Unauthorized",
    failed = "Failed",
    authorized = "Authorized",
    playingActivity = "Playing",
    streamingActivity = "Streaming",
    listeningActivity = "Listening",
    watchingActivity = "Watching",
    competingActivity = "Competing",
    languageSystem = "System",
)

val JapaneseText = KoreanText.copy(
    tabOverview = "概要",
    tabPrograms = "アプリ",
    tabPresence = "Presence",
    tabMusic = "音楽",
    tabPermissions = "権限",
    tabSettings = "設定",
    headerSubtitle = "Androidのアプリ使用状況と音楽再生情報をDiscord Rich Presenceへ送信します。",
    discordAutoConnectFailed = "Discordの自動接続に失敗しました。",
    discordAutoConnect = "Discord自動接続",
    foregroundAppTitle = "現在の前面アプリ",
    noDetectedApp = "検出されたアプリはありません",
    usageAccessMayBeRequired = "使用状況へのアクセス権限が必要な場合があります。",
    tracked = "登録済み",
    untracked = "未登録",
    discordConnect = "Discord接続",
    discordOnboardingBody = "初回起動時にDiscordアカウントを接続します。SDK認証が始まったら、DiscordアプリまたはWebログイン画面で承認を完了してください。",
    status = "状態",
    notConfiguredValue = "未設定",
    discordAuthStart = "Discord認証を開始します。DiscordアプリまたはWebログイン画面で承認を完了してください。",
    discordAccountConnected = "Discordアカウントを接続しました。",
    discordConnectFailed = "Discord接続に失敗しました。",
    connectAccount = "接続する",
    later = "後で",
    noConnectedAccount = "接続済みアカウントなし",
    registeredApps = "登録アプリ",
    appDetectionRunning = "アプリ検出実行中",
    appDetectionStopped = "アプリ検出停止中",
    currentApp = "現在のアプリ",
    unknown = "不明",
    displayOff = "表示オフ",
    noUsageInfo = "使用情報なし",
    canEnableInSettings = "設定で再度有効にできます。",
    music = "音楽",
    active = "有効",
    standby = "待機",
    noPlaybackInfo = "再生情報なし",
    currentDetectionInfo = "現在の検出情報",
    display = "表示",
    on = "オン",
    off = "オフ",
    appName = "アプリ名",
    hidden = "非表示",
    packageName = "パッケージ",
    registrationStatus = "登録状態",
    discordStatus = "Discord状態",
    lastError = "最後のエラー",
    authorization = "認証",
    account = "アカウント",
    none = "なし",
    userId = "ユーザーID",
    actions = "操作",
    reconnect = "再接続",
    connect = "接続",
    accountRefreshSuccess = "アカウント情報を更新しました。",
    accountRefreshFailed = "アカウント情報を読み込めませんでした。",
    refreshAccount = "アカウント更新",
    discordDisconnected = "Discord接続を解除しました。",
    disconnect = "接続解除",
    requirements = "必要条件",
    discordRequirementInstalled = "Discordアプリまたはブラウザのログイン画面でDiscordアカウントの承認を完了してください。",
    discordRequirementApplicationId = "Application IDはAndroidManifestのmanifest placeholderで注入されます。",
    discordRequirementRichPresence = "Rich Presenceの更新には接続済みDiscordアカウントの権限を使用します。",
    applicationIdNeedsCheck = "Application IDの確認が必要",
    appRichPresence = "アプリRich Presence",
    presenceCustomizer = "Presenceカスタマイズ",
    presenceCustomizerDescription = "登録済みアプリの現在のPresence設定を読み込んで直接編集します。",
    currentPresence = "現在のPresence",
    refreshPresence = "Presenceを更新",
    noRegisteredAppsForPresence = "Presenceを編集するには、先にアプリタブでアプリを登録してください。",
    selectPresenceApp = "編集するアプリ",
    presenceReloaded = "保存済みPresenceを再読み込みしました。",
    operation = "動作",
    running = "実行中",
    stopped = "停止中",
    notDetected = "未検出",
    startDetection = "検出開始",
    stop = "停止",
    appToRegister = "登録するアプリ",
    appRegistrationDescription = "パッケージ名と表示名を登録すると、そのアプリが前面にあるときDiscordに「アプリ名を使用中」と表示します。",
    displayName = "表示名",
    displayNameExample = "例: Chrome",
    chooseInstalledApp = "インストール済みアプリから選択",
    installedApps = "インストール済みアプリ",
    searchApps = "アプリ名またはパッケージを検索",
    showSystemApps = "システムアプリを表示",
    systemApp = "システム",
    noAppsFound = "検索結果がありません。",
    selectApp = "選択",
    alreadyRegistered = "登録済み",
    addManually = "手動で追加",
    addCurrentApp = "現在のアプリを追加",
    addAppleMusic = "Apple Musicを追加",
    enableForegroundHint = "現在のアプリ追加機能は、設定で前面アプリ表示を有効にすると使用できます。",
    currentDetected = "現在の検出",
    presenceSettings = "Presence設定",
    delete = "削除",
    activityType = "アクティビティ種別",
    detailText = "詳細テキスト",
    defaultDetailText = "{app}を使用中",
    stateText = "状態テキスト",
    defaultStateText = "使用中",
    templateHelp = "テキスト内で{app}, {package}, {title}を使用できます。",
    useAppIconForLargeImage = "アプリアイコンを大きい画像として使用",
    largeImageKeyOrUrl = "大きい画像キー/URL",
    discordAssetKeyOrUrl = "Discord asset keyまたはURL",
    largeImageText = "大きい画像の説明",
    imageHoverText = "画像のhoverテキスト",
    smallImageKeyOrUrl = "小さい画像キー/URL",
    smallImageText = "小さい画像の説明",
    partyCurrent = "パーティ現在人数",
    partyMax = "パーティ最大人数",
    save = "保存",
    cancel = "キャンセル",
    playbackStatus = "再生状態",
    playing = "再生中",
    track = "曲",
    artist = "アーティスト",
    album = "アルバム",
    albumImage = "アルバム画像",
    startMusicPresence = "音楽Presence開始",
    musicPlatforms = "音楽プラットフォーム",
    enabledPlatforms = "有効なプラットフォーム",
    startAllMusicPlatforms = "すべて開始",
    stopAll = "すべて停止",
    enable = "有効化",
    howItWorks = "動作方式",
    mediaSessionDescription = "Android MediaSessionから現在再生中のトラックを読み取ります。",
    artworkLookupDescription = "アルバムアートURLがない場合、iTunes Search APIの検索結果をキャッシュして使用します。",
    discordMusicDescription = "Discordには曲名、アーティスト、再生開始/終了時間が反映されます。",
    usageAccess = "使用状況へのアクセス",
    usageAccessDescription = "現在の前面アプリを検出し、登録アプリのPresenceを更新するために必要です。",
    notificationAccess = "通知へのアクセス",
    notificationAccessDescription = "MediaSessionの現在再生情報を安定して読み取るために必要です。",
    refreshPermissionStatus = "権限状態を更新",
    granted = "許可済み",
    required = "必要",
    settingsRequired = "設定が必要",
    openSettings = "設定を開く",
    appSettings = "アプリ設定",
    showForegroundApp = "前面アプリを表示",
    showForegroundAppDescription = "アプリ上部に現在開いているアプリ名とパッケージを表示します。",
    showForegroundAppNotification = "前面アプリ通知",
    showForegroundAppNotificationDescription = "現在の前面アプリをAndroid通知で表示し続けます。",
    notificationPermissionMissing = "通知権限がオフの場合は表示されません。",
    appNotificationPermission = "アプリ通知",
    appNotificationPermissionDescription = "現在の前面アプリを通知として表示するために必要です。",
    discordAutoConnectDescriptionOn = "次回起動からバックグラウンドでDiscord接続を試みます。",
    discordAutoConnectDescriptionOff = "次回起動時に初期接続ウィンドウを表示します。",
    language = "言語",
    registeredPackages = "登録済みパッケージ",
    customPresenceSettings = "個別Presence設定",
    configured = "設定済み",
    authorizing = "認証中",
    connecting = "接続中",
    ready = "準備完了",
    unauthorized = "未認証",
    failed = "失敗",
    authorized = "認証済み",
    playingActivity = "プレイ中",
    streamingActivity = "配信中",
    listeningActivity = "視聴中",
    watchingActivity = "観戦中",
    competingActivity = "競争中",
    languageSystem = "システム",
    languageJapanese = "日本語",
)
