package com.minepacu.craftpresence.ui.localization

import android.os.LocaleList
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalConfiguration
import com.minepacu.craftpresence.core.config.AppLanguage
import java.util.Locale

val LocalizedTextProvider = staticCompositionLocalOf { EnglishText }

@Immutable
data class LocalizedText(
    val tabOverview: String,
    val tabDiscord: String,
    val tabPrograms: String,
    val tabPresence: String,
    val tabMusic: String,
    val tabPermissions: String,
    val tabSettings: String,
    val headerSubtitle: String,
    val discordAutoConnectFailed: String,
    val discordAutoConnect: String,
    val foregroundAppTitle: String,
    val noDetectedApp: String,
    val usageAccessMayBeRequired: String,
    val tracked: String,
    val untracked: String,
    val discordConnect: String,
    val discordOnboardingTitle: String,
    val discordOnboardingBody: String,
    val discordOnboardingPriority: String,
    val status: String,
    val notConfiguredValue: String,
    val discordAuthStart: String,
    val discordAccountConnected: String,
    val discordConnectFailed: String,
    val connectAccount: String,
    val later: String,
    val noConnectedAccount: String,
    val registeredApps: String,
    val appDetectionRunning: String,
    val appDetectionStopped: String,
    val currentApp: String,
    val unknown: String,
    val displayOff: String,
    val noUsageInfo: String,
    val canEnableInSettings: String,
    val music: String,
    val active: String,
    val standby: String,
    val noPlaybackInfo: String,
    val currentDetectionInfo: String,
    val display: String,
    val on: String,
    val off: String,
    val appName: String,
    val hidden: String,
    val packageName: String,
    val registrationStatus: String,
    val discordStatus: String,
    val lastError: String,
    val authorization: String,
    val account: String,
    val none: String,
    val userId: String,
    val actions: String,
    val reconnect: String,
    val connect: String,
    val accountRefreshSuccess: String,
    val accountRefreshFailed: String,
    val refreshAccount: String,
    val discordDisconnected: String,
    val disconnect: String,
    val requirements: String,
    val discordRequirementInstalled: String,
    val discordRequirementApplicationId: String,
    val discordRequirementRichPresence: String,
    val applicationIdNeedsCheck: String,
    val appRichPresence: String,
    val presenceCustomizer: String,
    val presenceCustomizerDescription: String,
    val currentPresence: String,
    val actualPresence: String,
    val presenceSource: String,
    val appPresence: String,
    val musicPresence: String,
    val inactivePresence: String,
    val presenceDisconnected: String,
    val timestamps: String,
    val startTimestamp: String,
    val endTimestamp: String,
    val largeImage: String,
    val smallImage: String,
    val refreshPresence: String,
    val noRegisteredAppsForPresence: String,
    val selectPresenceApp: String,
    val presenceReloaded: String,
    val customPresenceDescription: String,
    val customPresenceDefaultTitle: String,
    val presetLibrary: String,
    val presetLibraryDescription: String,
    val newPreset: String,
    val newPresetTitle: String,
    val saveAsPreset: String,
    val publishNow: String,
    val clearPresence: String,
    val restoreDefaultPresets: String,
    val editPreset: String,
    val publish: String,
    val activePreset: String,
    val presetSaved: String,
    val presetDeleted: String,
    val presenceCleared: String,
    val defaultPresetsRestored: String,
    val noPresets: String,
    val previousPage: String,
    val nextPage: String,
    val presetPageLabel: (Int, Int) -> String,
    val presetTitle: String,
    val usesElapsedTime: String,
    val resetElapsedTimeOnPublish: String,
    val pausedElapsedDuration: (String) -> String,
    val usesParty: String,
    val operation: String,
    val running: String,
    val stopped: String,
    val notDetected: String,
    val startDetection: String,
    val stop: String,
    val appToRegister: String,
    val appRegistrationDescription: String,
    val displayName: String,
    val displayNameExample: String,
    val chooseInstalledApp: String,
    val installedApps: String,
    val searchApps: String,
    val showSystemApps: String,
    val systemApp: String,
    val noAppsFound: String,
    val selectApp: String,
    val alreadyRegistered: String,
    val addManually: String,
    val addCurrentApp: String,
    val addAppleMusic: String,
    val enableForegroundHint: String,
    val currentDetected: String,
    val presenceSettings: String,
    val delete: String,
    val activityType: String,
    val detailText: String,
    val defaultDetailText: String,
    val stateText: String,
    val defaultStateText: String,
    val templateHelp: String,
    val resetElapsedTimeOnPresenceChange: String,
    val useAppIconForLargeImage: String,
    val largeImageKeyOrUrl: String,
    val discordAssetKeyOrUrl: String,
    val largeImageText: String,
    val imageHoverText: String,
    val smallImageKeyOrUrl: String,
    val smallImageText: String,
    val partyCurrent: String,
    val partyMax: String,
    val ok: String,
    val save: String,
    val cancel: String,
    val playbackStatus: String,
    val playing: String,
    val track: String,
    val artist: String,
    val album: String,
    val albumImage: String,
    val startMusicPresence: String,
    val musicPlatforms: String,
    val enabledPlatforms: String,
    val startAllMusicPlatforms: String,
    val stopAll: String,
    val enable: String,
    val howItWorks: String,
    val mediaSessionDescription: String,
    val artworkLookupDescription: String,
    val discordMusicDescription: String,
    val usageAccess: String,
    val usageAccessDescription: String,
    val notificationAccess: String,
    val notificationAccessDescription: String,
    val refreshPermissionStatus: String,
    val granted: String,
    val required: String,
    val settingsRequired: String,
    val openSettings: String,
    val appSettings: String,
    val setupHealth: String,
    val setupHealthReady: String,
    val setupHealthNeedsAttention: String,
    val continueSetup: String,
    val settingsDestinations: String,
    val discordSettingsDescription: String,
    val trackedAppsSettingsDescription: String,
    val permissionsSettingsDescription: String,
    val backupAndRestore: String,
    val backupAndRestoreDescription: String,
    val nextRequiredPermission: String,
    val permissionReadyMessage: String,
    val usageAccessSettingsDestination: String,
    val appNotificationSettingsDestination: String,
    val notificationAccessSettingsDestination: String,
    val permissionReturnHint: String,
    val showForegroundApp: String,
    val showForegroundAppDescription: String,
    val showForegroundAppNotification: String,
    val showForegroundAppNotificationDescription: String,
    val notificationPermissionMissing: String,
    val appNotificationPermission: String,
    val appNotificationPermissionDescription: String,
    val discordAutoConnectDescriptionOn: String,
    val discordAutoConnectDescriptionOff: String,
    val resetElapsedTimeOnScheduledPresetRestore: String,
    val resetElapsedTimeOnScheduledPresetRestoreDescription: String,
    val language: String,
    val registeredPackages: String,
    val customPresenceSettings: String,
    val settingsImportExport: String,
    val settingsImportExportDescription: String,
    val settingsExport: String,
    val settingsExportSuccess: String,
    val settingsExportOpenFailed: String,
    val settingsImport: String,
    val settingsImportSuccess: String,
    val settingsImportOpenFailed: String,
    val settingsImportConfirmTitle: String,
    val settingsImportConfirmMessage: String,
    val settingsTransferError: String,
    val settingsTransferResult: String,
    val configured: String,
    val authorizing: String,
    val connecting: String,
    val ready: String,
    val unauthorized: String,
    val failed: String,
    val authorized: String,
    val playingActivity: String,
    val streamingActivity: String,
    val listeningActivity: String,
    val watchingActivity: String,
    val competingActivity: String,
    val languageSystem: String,
    val languageKorean: String,
    val languageEnglish: String,
    val languageJapanese: String,
) {
    fun countItems(count: Int): String = when (this) {
        KoreanText -> "${count}개"
        JapaneseText -> "${count}件"
        else -> "$count"
    }

    fun currentDetectedValue(value: String): String = when (this) {
        KoreanText -> "$currentDetected: $value"
        JapaneseText -> "$currentDetected: $value"
        else -> "$currentDetected: $value"
    }

    fun presetPublished(title: String): String = when (this) {
        KoreanText -> "$title 프리셋을 게시했습니다."
        JapaneseText -> "$title プリセットを公開しました。"
        else -> "Published $title."
    }
}

@Composable
fun rememberLocalizedText(language: AppLanguage): LocalizedText {
    val configuration = LocalConfiguration.current
    return remember(language, configuration) {
        val systemLocale = configuration.locales.firstOrNullCompat() ?: Locale.getDefault()
        when (language) {
            AppLanguage.SYSTEM -> textFor(systemLocale.language)
            AppLanguage.KOREAN -> KoreanText
            AppLanguage.ENGLISH -> EnglishText
            AppLanguage.JAPANESE -> JapaneseText
        }
    }
}

private fun LocaleList.firstOrNullCompat(): Locale? = if (size() == 0) null else get(0)

private fun textFor(languageCode: String): LocalizedText = when (languageCode.lowercase(Locale.ROOT)) {
    "ko" -> KoreanText
    "ja" -> JapaneseText
    else -> EnglishText
}

val KoreanText = LocalizedText(
    tabOverview = "개요",
    tabDiscord = "Discord",
    tabPrograms = "앱",
    tabPresence = "Presence",
    tabMusic = "음악",
    tabPermissions = "권한",
    tabSettings = "설정",
    headerSubtitle = "Android에서 앱 사용 상태와 음악 재생 정보를 Discord Rich Presence로 보냅니다.",
    discordAutoConnectFailed = "Discord 자동 연결에 실패했습니다.",
    discordAutoConnect = "Discord 자동 연결",
    foregroundAppTitle = "현재 포그라운드 앱",
    noDetectedApp = "감지된 앱 없음",
    usageAccessMayBeRequired = "사용 정보 접근 권한이 필요할 수 있습니다.",
    tracked = "등록됨",
    untracked = "미등록",
    discordConnect = "Discord 연결",
    discordOnboardingTitle = "시작 전에 Discord를 연결하세요",
    discordOnboardingBody = "처음 실행할 때 Discord 계정을 연결합니다. SDK 인증이 시작되면 Discord 앱 또는 웹 로그인 화면에서 계정 승인을 완료해야 합니다.",
    discordOnboardingPriority = "Discord 연결이 첫 설정 단계입니다.",
    status = "상태",
    notConfiguredValue = "설정되지 않음",
    discordAuthStart = "Discord 인증을 시작합니다. Discord 앱 또는 웹 로그인 화면에서 승인을 완료해 주세요.",
    discordAccountConnected = "Discord 계정이 연결되었습니다.",
    discordConnectFailed = "Discord 연결에 실패했습니다.",
    connectAccount = "연결하기",
    later = "나중에",
    noConnectedAccount = "연결된 계정 없음",
    registeredApps = "등록 앱",
    appDetectionRunning = "앱 감지 실행 중",
    appDetectionStopped = "앱 감지 중지됨",
    currentApp = "현재 앱",
    unknown = "알 수 없음",
    displayOff = "표시 꺼짐",
    noUsageInfo = "사용 정보 없음",
    canEnableInSettings = "설정에서 다시 켤 수 있습니다.",
    music = "음악",
    active = "활성",
    standby = "대기",
    noPlaybackInfo = "재생 정보 없음",
    currentDetectionInfo = "현재 감지 정보",
    display = "표시",
    on = "켜짐",
    off = "꺼짐",
    appName = "앱 이름",
    hidden = "숨김",
    packageName = "패키지",
    registrationStatus = "등록 여부",
    discordStatus = "Discord 상태",
    lastError = "마지막 오류",
    authorization = "인증",
    account = "계정",
    none = "없음",
    userId = "사용자 ID",
    actions = "작업",
    reconnect = "다시 연결",
    connect = "연결",
    accountRefreshSuccess = "계정 정보를 새로 불러왔습니다.",
    accountRefreshFailed = "계정 정보를 불러오지 못했습니다.",
    refreshAccount = "계정 새로고침",
    discordDisconnected = "Discord 연결을 해제했습니다.",
    disconnect = "연결 해제",
    requirements = "필요 조건",
    discordRequirementInstalled = "Discord 앱 또는 브라우저 로그인 화면에서 Discord 계정 승인을 완료해야 합니다.",
    discordRequirementApplicationId = "Application ID는 AndroidManifest manifest placeholder로 주입됩니다.",
    discordRequirementRichPresence = "Rich Presence 갱신은 연결된 Discord 계정 권한을 사용합니다.",
    applicationIdNeedsCheck = "Application ID 확인 필요",
    appRichPresence = "앱 Rich Presence",
    presenceCustomizer = "Presence 커스터마이징",
    presenceCustomizerDescription = "등록된 앱의 현재 Presence 설정을 불러와 직접 수정합니다.",
    currentPresence = "현재 Presence",
    actualPresence = "전송 중인 Presence",
    presenceSource = "Presence 출처",
    appPresence = "앱 Presence",
    musicPresence = "음악 Presence",
    inactivePresence = "현재 전송 중인 Presence가 없습니다.",
    presenceDisconnected = "Discord가 연결되어 있지 않아 Presence를 전송하지 않습니다.",
    timestamps = "타임스탬프",
    startTimestamp = "시작 시간",
    endTimestamp = "종료 시간",
    largeImage = "큰 이미지",
    smallImage = "작은 이미지",
    refreshPresence = "Presence 새로고침",
    noRegisteredAppsForPresence = "Presence를 수정하려면 먼저 앱 탭에서 앱을 등록하세요.",
    selectPresenceApp = "Presence를 수정할 앱",
    presenceReloaded = "저장된 Presence를 다시 불러왔습니다.",
    customPresenceDescription = "Discord에 보낼 Rich Presence를 직접 구성하고 바로 게시하거나 프리셋으로 저장합니다.",
    customPresenceDefaultTitle = "커스텀 Presence",
    presetLibrary = "Presence 프리셋",
    presetLibraryDescription = "자주 쓰는 Discord Rich Presence를 저장하고 필요할 때 바로 게시합니다.",
    newPreset = "프리셋 만들기",
    newPresetTitle = "새 프리셋",
    saveAsPreset = "프리셋으로 저장",
    publishNow = "지금 게시",
    clearPresence = "Presence 지우기",
    restoreDefaultPresets = "기본 프리셋 복원",
    editPreset = "프리셋 편집",
    publish = "게시",
    activePreset = "게시 중",
    presetSaved = "프리셋을 저장했습니다.",
    presetDeleted = "프리셋을 삭제했습니다.",
    presenceCleared = "Discord Presence를 지웠습니다.",
    defaultPresetsRestored = "누락된 기본 프리셋을 복원했습니다.",
    noPresets = "저장된 프리셋이 없습니다.",
    previousPage = "이전",
    nextPage = "다음",
    presetPageLabel = { current, total -> "$current / $total 페이지" },
    presetTitle = "프리셋 이름",
    usesElapsedTime = "경과 시간 표시",
    resetElapsedTimeOnPublish = "게시 시 경과 시간 초기화",
    pausedElapsedDuration = { "중단 당시 경과: $it" },
    usesParty = "파티 인원 표시",
    operation = "동작",
    running = "실행 중",
    stopped = "중지됨",
    notDetected = "감지 안 됨",
    startDetection = "감지 시작",
    stop = "중지",
    appToRegister = "등록할 앱",
    appRegistrationDescription = "패키지 이름과 표시 이름을 등록하면 해당 앱이 전면에 있을 때 Discord에 \"앱 이름 앱 사용 중\"으로 표시합니다.",
    displayName = "표시 이름",
    displayNameExample = "예: Chrome",
    chooseInstalledApp = "설치된 앱에서 선택",
    installedApps = "설치된 앱",
    searchApps = "앱 이름 또는 패키지 검색",
    showSystemApps = "시스템 앱 표시",
    systemApp = "시스템",
    noAppsFound = "검색 결과가 없습니다.",
    selectApp = "선택",
    alreadyRegistered = "등록됨",
    addManually = "직접 추가",
    addCurrentApp = "현재 앱 추가",
    addAppleMusic = "Apple Music 추가",
    enableForegroundHint = "현재 앱 추가 기능은 설정에서 포그라운드 앱 표시를 켜면 사용할 수 있습니다.",
    currentDetected = "현재 감지",
    presenceSettings = "Presence 설정",
    delete = "삭제",
    activityType = "활동 유형",
    detailText = "상세 문구",
    defaultDetailText = "{app} 앱 사용 중",
    stateText = "상태 문구",
    defaultStateText = "사용 중",
    templateHelp = "{app}, {package}, {title} 값을 문구 안에 사용할 수 있습니다.",
    resetElapsedTimeOnPresenceChange = "Presence 변경 시 경과 시간 초기화",
    useAppIconForLargeImage = "앱 아이콘을 큰 이미지로 사용",
    largeImageKeyOrUrl = "큰 이미지 키/URL",
    discordAssetKeyOrUrl = "Discord asset key 또는 URL",
    largeImageText = "큰 이미지 설명",
    imageHoverText = "이미지 hover 텍스트",
    smallImageKeyOrUrl = "작은 이미지 키/URL",
    smallImageText = "작은 이미지 설명",
    partyCurrent = "파티 현재 인원",
    partyMax = "파티 최대 인원",
    ok = "확인",
    save = "저장",
    cancel = "취소",
    playbackStatus = "재생 상태",
    playing = "재생 중",
    track = "곡",
    artist = "아티스트",
    album = "앨범",
    albumImage = "앨범 이미지",
    startMusicPresence = "음악 Presence 시작",
    musicPlatforms = "음악 플랫폼",
    enabledPlatforms = "활성 플랫폼",
    startAllMusicPlatforms = "전체 시작",
    stopAll = "전체 중지",
    enable = "켜기",
    howItWorks = "동작 방식",
    mediaSessionDescription = "Android MediaSession에서 현재 재생 중인 트랙을 읽습니다.",
    artworkLookupDescription = "앨범 아트 URL이 없으면 iTunes Search API 조회 결과를 캐시해 사용합니다.",
    discordMusicDescription = "Discord에는 곡명, 아티스트, 재생 시작/종료 시간이 반영됩니다.",
    usageAccess = "사용 정보 접근",
    usageAccessDescription = "현재 전면 앱을 감지해 등록된 앱의 Presence를 갱신할 때 필요합니다.",
    notificationAccess = "알림 접근",
    notificationAccessDescription = "MediaSession의 현재 재생 정보를 안정적으로 읽을 때 필요합니다.",
    refreshPermissionStatus = "권한 상태 새로고침",
    granted = "허용됨",
    required = "필요함",
    settingsRequired = "설정 필요",
    openSettings = "설정 열기",
    appSettings = "앱 설정",
    setupHealth = "설정 상태",
    setupHealthReady = "필요한 설정이 완료되었습니다.",
    setupHealthNeedsAttention = "아직 완료해야 할 Android 설정이 있습니다.",
    continueSetup = "설정 계속하기",
    settingsDestinations = "설정 바로가기",
    discordSettingsDescription = "계정 연결, Application ID, 재연결",
    trackedAppsSettingsDescription = "앱 등록과 Presence 프리셋 관리",
    permissionsSettingsDescription = "사용 정보, 앱 알림, 알림 접근 권한",
    backupAndRestore = "백업 및 복원",
    backupAndRestoreDescription = "설정 JSON 파일 가져오기/내보내기",
    nextRequiredPermission = "다음으로 필요한 권한",
    permissionReadyMessage = "필요한 권한이 모두 허용되었습니다.",
    usageAccessSettingsDestination = "Android 사용 정보 접근 설정에서 CraftPresence를 허용하세요.",
    appNotificationSettingsDestination = "Android 앱 알림 설정에서 CraftPresence 알림을 허용하세요.",
    notificationAccessSettingsDestination = "Android 알림 접근 설정에서 CraftPresence를 허용하세요.",
    permissionReturnHint = "설정을 마친 뒤 앱으로 돌아와 권한 상태를 새로고침하세요.",
    showForegroundApp = "포그라운드 앱 표시",
    showForegroundAppDescription = "앱 상단에 현재 열려 있는 앱 이름과 패키지를 표시합니다.",
    showForegroundAppNotification = "포그라운드 앱 알림",
    showForegroundAppNotificationDescription = "현재 전면 앱을 Android 알림으로 계속 표시합니다.",
    notificationPermissionMissing = "알림 권한이 꺼져 있으면 표시되지 않습니다.",
    appNotificationPermission = "앱 알림",
    appNotificationPermissionDescription = "현재 포그라운드 앱을 알림으로 표시할 때 필요합니다.",
    discordAutoConnectDescriptionOn = "다음 실행부터 백그라운드에서 Discord 연결을 시도합니다.",
    discordAutoConnectDescriptionOff = "다음 실행 시 초기 연결 창을 표시합니다.",
    resetElapsedTimeOnScheduledPresetRestore = "예약 Presence 복원 시 경과 시간 초기화",
    resetElapsedTimeOnScheduledPresetRestoreDescription = "예약 프리셋이 끝나 이전 Presence를 복원할 때 시작 시간을 현재 시각으로 다시 설정합니다.",
    language = "언어",
    registeredPackages = "등록된 패키지",
    customPresenceSettings = "개별 Presence 설정",
    settingsImportExport = "설정 가져오기/내보내기",
    settingsImportExportDescription = "등록 앱, 표시 이름, Presence 설정을 JSON 파일로 저장하거나 가져옵니다.",
    settingsExport = "내보내기",
    settingsExportSuccess = "설정 JSON 파일을 내보냈습니다.",
    settingsExportOpenFailed = "내보낼 파일을 열 수 없습니다.",
    settingsImport = "가져오기",
    settingsImportSuccess = "설정을 가져왔습니다.",
    settingsImportOpenFailed = "가져올 파일을 열 수 없습니다.",
    settingsImportConfirmTitle = "설정을 가져올까요?",
    settingsImportConfirmMessage = "현재 설정이 JSON 파일의 설정으로 교체됩니다.",
    settingsTransferError = "설정 파일을 처리하지 못했습니다.",
    settingsTransferResult = "설정 파일",
    configured = "설정됨",
    authorizing = "인증 중",
    connecting = "연결 중",
    ready = "준비됨",
    unauthorized = "미인증",
    failed = "실패",
    authorized = "인증됨",
    playingActivity = "플레이",
    streamingActivity = "스트리밍",
    listeningActivity = "듣는 중",
    watchingActivity = "시청 중",
    competingActivity = "경쟁 중",
    languageSystem = "시스템",
    languageKorean = "한국어",
    languageEnglish = "English",
    languageJapanese = "日本語",
)

val EnglishText = KoreanText.copy(
    tabOverview = "Overview",
    tabPrograms = "Apps",
    tabPresence = "Presence",
    tabMusic = "Music",
    tabPermissions = "Permissions",
    tabSettings = "Settings",
    headerSubtitle = "Send app usage and music playback status from Android to Discord Rich Presence.",
    discordAutoConnectFailed = "Discord auto-connect failed.",
    discordAutoConnect = "Discord auto-connect",
    foregroundAppTitle = "Current foreground app",
    noDetectedApp = "No app detected",
    usageAccessMayBeRequired = "Usage access permission may be required.",
    tracked = "Registered",
    untracked = "Not registered",
    discordConnect = "Discord connection",
    discordOnboardingTitle = "Connect Discord before you start",
    discordOnboardingBody = "Connect your Discord account on first launch. When SDK authorization starts, finish account approval in the Discord app or web login screen.",
    discordOnboardingPriority = "Discord connection is the first setup step.",
    status = "Status",
    notConfiguredValue = "Not configured",
    discordAuthStart = "Starting Discord authorization. Finish approval in the Discord app or web login screen.",
    discordAccountConnected = "Discord account connected.",
    discordConnectFailed = "Discord connection failed.",
    connectAccount = "Connect",
    later = "Later",
    noConnectedAccount = "No connected account",
    registeredApps = "Registered apps",
    appDetectionRunning = "App detection running",
    appDetectionStopped = "App detection stopped",
    currentApp = "Current app",
    unknown = "Unknown",
    displayOff = "Display off",
    noUsageInfo = "No usage info",
    canEnableInSettings = "You can enable it again in Settings.",
    music = "Music",
    active = "Active",
    standby = "Standby",
    noPlaybackInfo = "No playback info",
    currentDetectionInfo = "Current detection",
    display = "Display",
    on = "On",
    off = "Off",
    appName = "App name",
    hidden = "Hidden",
    registrationStatus = "Registration",
    discordStatus = "Discord status",
    lastError = "Last error",
    authorization = "Authorization",
    account = "Account",
    none = "None",
    userId = "User ID",
    actions = "Actions",
    reconnect = "Reconnect",
    connect = "Connect",
    accountRefreshSuccess = "Account information refreshed.",
    accountRefreshFailed = "Could not load account information.",
    refreshAccount = "Refresh account",
    discordDisconnected = "Disconnected from Discord.",
    disconnect = "Disconnect",
    requirements = "Requirements",
    discordRequirementInstalled = "Approve your Discord account in the Discord app or browser login screen.",
    discordRequirementApplicationId = "Application ID is injected through the AndroidManifest manifest placeholder.",
    discordRequirementRichPresence = "Rich Presence updates use the connected Discord account permissions.",
    applicationIdNeedsCheck = "Application ID needs review",
    appRichPresence = "App Rich Presence",
    presenceCustomizer = "Presence customization",
    presenceCustomizerDescription = "Load and edit the current Presence settings for registered apps.",
    currentPresence = "Current Presence",
    actualPresence = "Presence being sent",
    presenceSource = "Presence source",
    appPresence = "App Presence",
    musicPresence = "Music Presence",
    inactivePresence = "No Presence is currently being sent.",
    presenceDisconnected = "Discord is not connected, so Presence is not being sent.",
    timestamps = "Timestamps",
    startTimestamp = "Start time",
    endTimestamp = "End time",
    largeImage = "Large image",
    smallImage = "Small image",
    refreshPresence = "Refresh Presence",
    noRegisteredAppsForPresence = "Register an app in the Apps tab before editing Presence.",
    selectPresenceApp = "App to edit",
    presenceReloaded = "Reloaded saved Presence.",
    customPresenceDescription = "Compose the Discord Rich Presence payload directly, then publish it now or save it as a preset.",
    customPresenceDefaultTitle = "Custom Presence",
    presetLibrary = "Presence presets",
    presetLibraryDescription = "Save frequently used Discord Rich Presence payloads and publish them when needed.",
    newPreset = "Create preset",
    newPresetTitle = "New preset",
    saveAsPreset = "Save as preset",
    publishNow = "Publish now",
    clearPresence = "Clear Presence",
    restoreDefaultPresets = "Restore default presets",
    editPreset = "Edit preset",
    publish = "Publish",
    activePreset = "Active",
    presetSaved = "Preset saved.",
    presetDeleted = "Preset deleted.",
    presenceCleared = "Discord Presence cleared.",
    defaultPresetsRestored = "Missing default presets restored.",
    noPresets = "No saved presets.",
    previousPage = "Previous",
    nextPage = "Next",
    presetPageLabel = { current, total -> "Page $current / $total" },
    presetTitle = "Preset name",
    usesElapsedTime = "Show elapsed time",
    resetElapsedTimeOnPublish = "Reset elapsed time on publish",
    pausedElapsedDuration = { "Paused after $it elapsed" },
    usesParty = "Show party size",
    operation = "Operation",
    running = "Running",
    stopped = "Stopped",
    notDetected = "Not detected",
    startDetection = "Start detection",
    stop = "Stop",
    appToRegister = "App to register",
    appRegistrationDescription = "Register a package name and display name to show \"Using app name\" on Discord when that app is in front.",
    packageName = "Package name",
    displayName = "Display name",
    displayNameExample = "Example: Chrome",
    chooseInstalledApp = "Choose installed app",
    installedApps = "Installed apps",
    searchApps = "Search app name or package",
    showSystemApps = "Show system apps",
    systemApp = "System",
    noAppsFound = "No apps found.",
    selectApp = "Select",
    alreadyRegistered = "Registered",
    addManually = "Add manually",
    addCurrentApp = "Add current app",
    addAppleMusic = "Add Apple Music",
    enableForegroundHint = "Enable foreground app display in Settings to use Add current app.",
    currentDetected = "Current detection",
    presenceSettings = "Presence settings",
    delete = "Delete",
    activityType = "Activity type",
    detailText = "Details text",
    defaultDetailText = "Using {app}",
    stateText = "State text",
    defaultStateText = "In use",
    templateHelp = "You can use {app}, {package}, and {title} in the text.",
    resetElapsedTimeOnPresenceChange = "Reset elapsed time when Presence changes",
    useAppIconForLargeImage = "Use app icon as large image",
    largeImageKeyOrUrl = "Large image key/URL",
    discordAssetKeyOrUrl = "Discord asset key or URL",
    largeImageText = "Large image text",
    imageHoverText = "Image hover text",
    smallImageKeyOrUrl = "Small image key/URL",
    smallImageText = "Small image text",
    partyCurrent = "Party current size",
    partyMax = "Party max size",
    ok = "OK",
    save = "Save",
    cancel = "Cancel",
    playbackStatus = "Playback status",
    playing = "Playing",
    track = "Track",
    artist = "Artist",
    album = "Album",
    albumImage = "Album image",
    startMusicPresence = "Start music Presence",
    musicPlatforms = "Music platforms",
    enabledPlatforms = "Enabled platforms",
    startAllMusicPlatforms = "Start all",
    stopAll = "Stop all",
    enable = "Enable",
    howItWorks = "How it works",
    mediaSessionDescription = "Reads the currently playing track from Android MediaSession.",
    artworkLookupDescription = "If album artwork URL is missing, caches results from the iTunes Search API.",
    discordMusicDescription = "Discord receives the track title, artist, and playback start/end time.",
    usageAccess = "Usage access",
    usageAccessDescription = "Required to detect the foreground app and update Presence for registered apps.",
    notificationAccess = "Notification access",
    notificationAccessDescription = "Required to reliably read current playback information from MediaSession.",
    refreshPermissionStatus = "Refresh permission status",
    granted = "Allowed",
    required = "Required",
    settingsRequired = "Settings required",
    openSettings = "Open settings",
    appSettings = "App settings",
    setupHealth = "Setup health",
    setupHealthReady = "Required setup is complete.",
    setupHealthNeedsAttention = "Some Android setup items still need attention.",
    continueSetup = "Continue setup",
    settingsDestinations = "Settings shortcuts",
    discordSettingsDescription = "Account connection, Application ID, reconnect",
    trackedAppsSettingsDescription = "Register apps and manage Presence presets",
    permissionsSettingsDescription = "Usage access, app notifications, notification access",
    backupAndRestore = "Backup and restore",
    backupAndRestoreDescription = "Import or export settings JSON files",
    nextRequiredPermission = "Next required permission",
    permissionReadyMessage = "All required permissions are allowed.",
    usageAccessSettingsDestination = "In Android Usage access settings, allow CraftPresence.",
    appNotificationSettingsDestination = "In Android app notification settings, allow CraftPresence notifications.",
    notificationAccessSettingsDestination = "In Android Notification access settings, allow CraftPresence.",
    permissionReturnHint = "After changing the setting, return to the app and refresh permission status.",
    showForegroundApp = "Show foreground app",
    showForegroundAppDescription = "Shows the currently open app name and package at the top of the app.",
    showForegroundAppNotification = "Foreground app notification",
    showForegroundAppNotificationDescription = "Keeps the current foreground app visible in an Android notification.",
    notificationPermissionMissing = "It will not appear while notification permission is off.",
    appNotificationPermission = "App notifications",
    appNotificationPermissionDescription = "Required to show the current foreground app as a notification.",
    discordAutoConnectDescriptionOn = "The app will try to connect to Discord in the background from the next launch.",
    discordAutoConnectDescriptionOff = "The initial connection dialog will appear on the next launch.",
    resetElapsedTimeOnScheduledPresetRestore = "Reset elapsed time on scheduled restore",
    resetElapsedTimeOnScheduledPresetRestoreDescription = "When a scheduled preset ends and the previous Presence is restored, set its start time to now.",
    language = "Language",
    registeredPackages = "Registered packages",
    customPresenceSettings = "Custom Presence settings",
    settingsImportExport = "Settings import/export",
    settingsImportExportDescription = "Save or restore registered apps, display names, and Presence settings as a JSON file.",
    settingsExport = "Export",
    settingsExportSuccess = "Settings JSON file exported.",
    settingsExportOpenFailed = "Could not open the export file.",
    settingsImport = "Import",
    settingsImportSuccess = "Settings imported.",
    settingsImportOpenFailed = "Could not open the import file.",
    settingsImportConfirmTitle = "Import settings?",
    settingsImportConfirmMessage = "Current settings will be replaced with the settings from the JSON file.",
    settingsTransferError = "Could not process the settings file.",
    settingsTransferResult = "Settings file",
    configured = "Configured",
    authorizing = "Authorizing",
    connecting = "Connecting",
    ready = "Ready",
    unauthorized = "Unauthorized",
    failed = "Failed",
    authorized = "Authorized",
    playingActivity = "Playing",
    streamingActivity = "Streaming",
    listeningActivity = "Listening",
    watchingActivity = "Watching",
    competingActivity = "Competing",
    languageSystem = "System",
)

val JapaneseText = KoreanText.copy(
    tabOverview = "概要",
    tabPrograms = "アプリ",
    tabPresence = "Presence",
    tabMusic = "音楽",
    tabPermissions = "権限",
    tabSettings = "設定",
    headerSubtitle = "Androidのアプリ使用状況と音楽再生情報をDiscord Rich Presenceへ送信します。",
    discordAutoConnectFailed = "Discordの自動接続に失敗しました。",
    discordAutoConnect = "Discord自動接続",
    foregroundAppTitle = "現在の前面アプリ",
    noDetectedApp = "検出されたアプリはありません",
    usageAccessMayBeRequired = "使用状況へのアクセス権限が必要な場合があります。",
    tracked = "登録済み",
    untracked = "未登録",
    discordConnect = "Discord接続",
    discordOnboardingTitle = "開始前にDiscordを接続してください",
    discordOnboardingBody = "初回起動時にDiscordアカウントを接続します。SDK認証が始まったら、DiscordアプリまたはWebログイン画面で承認を完了してください。",
    discordOnboardingPriority = "Discord接続が最初の設定ステップです。",
    status = "状態",
    notConfiguredValue = "未設定",
    discordAuthStart = "Discord認証を開始します。DiscordアプリまたはWebログイン画面で承認を完了してください。",
    discordAccountConnected = "Discordアカウントを接続しました。",
    discordConnectFailed = "Discord接続に失敗しました。",
    connectAccount = "接続する",
    later = "後で",
    noConnectedAccount = "接続済みアカウントなし",
    registeredApps = "登録アプリ",
    appDetectionRunning = "アプリ検出実行中",
    appDetectionStopped = "アプリ検出停止中",
    currentApp = "現在のアプリ",
    unknown = "不明",
    displayOff = "表示オフ",
    noUsageInfo = "使用情報なし",
    canEnableInSettings = "設定で再度有効にできます。",
    music = "音楽",
    active = "有効",
    standby = "待機",
    noPlaybackInfo = "再生情報なし",
    currentDetectionInfo = "現在の検出情報",
    display = "表示",
    on = "オン",
    off = "オフ",
    appName = "アプリ名",
    hidden = "非表示",
    packageName = "パッケージ",
    registrationStatus = "登録状態",
    discordStatus = "Discord状態",
    lastError = "最後のエラー",
    authorization = "認証",
    account = "アカウント",
    none = "なし",
    userId = "ユーザーID",
    actions = "操作",
    reconnect = "再接続",
    connect = "接続",
    accountRefreshSuccess = "アカウント情報を更新しました。",
    accountRefreshFailed = "アカウント情報を読み込めませんでした。",
    refreshAccount = "アカウント更新",
    discordDisconnected = "Discord接続を解除しました。",
    disconnect = "接続解除",
    requirements = "必要条件",
    discordRequirementInstalled = "Discordアプリまたはブラウザのログイン画面でDiscordアカウントの承認を完了してください。",
    discordRequirementApplicationId = "Application IDはAndroidManifestのmanifest placeholderで注入されます。",
    discordRequirementRichPresence = "Rich Presenceの更新には接続済みDiscordアカウントの権限を使用します。",
    applicationIdNeedsCheck = "Application IDの確認が必要",
    appRichPresence = "アプリRich Presence",
    presenceCustomizer = "Presenceカスタマイズ",
    presenceCustomizerDescription = "登録済みアプリの現在のPresence設定を読み込んで直接編集します。",
    currentPresence = "現在のPresence",
    actualPresence = "送信中のPresence",
    presenceSource = "Presenceの種類",
    appPresence = "アプリPresence",
    musicPresence = "音楽Presence",
    inactivePresence = "現在送信中のPresenceはありません。",
    presenceDisconnected = "Discordに接続されていないため、Presenceを送信していません。",
    timestamps = "タイムスタンプ",
    startTimestamp = "開始時刻",
    endTimestamp = "終了時刻",
    largeImage = "大きい画像",
    smallImage = "小さい画像",
    refreshPresence = "Presenceを更新",
    noRegisteredAppsForPresence = "Presenceを編集するには、先にアプリタブでアプリを登録してください。",
    selectPresenceApp = "編集するアプリ",
    presenceReloaded = "保存済みPresenceを再読み込みしました。",
    customPresenceDescription = "Discordに送信するRich Presenceを直接構成し、すぐ公開するかプリセットとして保存します。",
    customPresenceDefaultTitle = "カスタムPresence",
    presetLibrary = "Presenceプリセット",
    presetLibraryDescription = "よく使うDiscord Rich Presenceを保存し、必要なときに公開します。",
    newPreset = "プリセット作成",
    newPresetTitle = "新しいプリセット",
    saveAsPreset = "プリセットとして保存",
    publishNow = "今すぐ公開",
    clearPresence = "Presenceを消去",
    restoreDefaultPresets = "既定プリセットを復元",
    editPreset = "プリセット編集",
    publish = "公開",
    activePreset = "公開中",
    presetSaved = "プリセットを保存しました。",
    presetDeleted = "プリセットを削除しました。",
    presenceCleared = "Discord Presenceを消去しました。",
    defaultPresetsRestored = "不足している既定プリセットを復元しました。",
    noPresets = "保存済みプリセットはありません。",
    previousPage = "前へ",
    nextPage = "次へ",
    presetPageLabel = { current, total -> "$current / $total ページ" },
    presetTitle = "プリセット名",
    usesElapsedTime = "経過時間を表示",
    resetElapsedTimeOnPublish = "公開時に経過時間をリセット",
    pausedElapsedDuration = { "一時停止時の経過: $it" },
    usesParty = "パーティ人数を表示",
    operation = "動作",
    running = "実行中",
    stopped = "停止中",
    notDetected = "未検出",
    startDetection = "検出開始",
    stop = "停止",
    appToRegister = "登録するアプリ",
    appRegistrationDescription = "パッケージ名と表示名を登録すると、そのアプリが前面にあるときDiscordに「アプリ名を使用中」と表示します。",
    displayName = "表示名",
    displayNameExample = "例: Chrome",
    chooseInstalledApp = "インストール済みアプリから選択",
    installedApps = "インストール済みアプリ",
    searchApps = "アプリ名またはパッケージを検索",
    showSystemApps = "システムアプリを表示",
    systemApp = "システム",
    noAppsFound = "検索結果がありません。",
    selectApp = "選択",
    alreadyRegistered = "登録済み",
    addManually = "手動で追加",
    addCurrentApp = "現在のアプリを追加",
    addAppleMusic = "Apple Musicを追加",
    enableForegroundHint = "現在のアプリ追加機能は、設定で前面アプリ表示を有効にすると使用できます。",
    currentDetected = "現在の検出",
    presenceSettings = "Presence設定",
    delete = "削除",
    activityType = "アクティビティ種別",
    detailText = "詳細テキスト",
    defaultDetailText = "{app}を使用中",
    stateText = "状態テキスト",
    defaultStateText = "使用中",
    templateHelp = "テキスト内で{app}, {package}, {title}を使用できます。",
    resetElapsedTimeOnPresenceChange = "Presence変更時に経過時間をリセット",
    useAppIconForLargeImage = "アプリアイコンを大きい画像として使用",
    largeImageKeyOrUrl = "大きい画像キー/URL",
    discordAssetKeyOrUrl = "Discord asset keyまたはURL",
    largeImageText = "大きい画像の説明",
    imageHoverText = "画像のhoverテキスト",
    smallImageKeyOrUrl = "小さい画像キー/URL",
    smallImageText = "小さい画像の説明",
    partyCurrent = "パーティ現在人数",
    partyMax = "パーティ最大人数",
    ok = "OK",
    save = "保存",
    cancel = "キャンセル",
    playbackStatus = "再生状態",
    playing = "再生中",
    track = "曲",
    artist = "アーティスト",
    album = "アルバム",
    albumImage = "アルバム画像",
    startMusicPresence = "音楽Presence開始",
    musicPlatforms = "音楽プラットフォーム",
    enabledPlatforms = "有効なプラットフォーム",
    startAllMusicPlatforms = "すべて開始",
    stopAll = "すべて停止",
    enable = "有効化",
    howItWorks = "動作方式",
    mediaSessionDescription = "Android MediaSessionから現在再生中のトラックを読み取ります。",
    artworkLookupDescription = "アルバムアートURLがない場合、iTunes Search APIの検索結果をキャッシュして使用します。",
    discordMusicDescription = "Discordには曲名、アーティスト、再生開始/終了時間が反映されます。",
    usageAccess = "使用状況へのアクセス",
    usageAccessDescription = "現在の前面アプリを検出し、登録アプリのPresenceを更新するために必要です。",
    notificationAccess = "通知へのアクセス",
    notificationAccessDescription = "MediaSessionの現在再生情報を安定して読み取るために必要です。",
    refreshPermissionStatus = "権限状態を更新",
    granted = "許可済み",
    required = "必要",
    settingsRequired = "設定が必要",
    openSettings = "設定を開く",
    appSettings = "アプリ設定",
    setupHealth = "設定状態",
    setupHealthReady = "必要な設定は完了しています。",
    setupHealthNeedsAttention = "まだ対応が必要なAndroid設定があります。",
    continueSetup = "設定を続ける",
    settingsDestinations = "設定ショートカット",
    discordSettingsDescription = "アカウント接続、Application ID、再接続",
    trackedAppsSettingsDescription = "アプリ登録とPresenceプリセット管理",
    permissionsSettingsDescription = "使用状況、アプリ通知、通知アクセス権限",
    backupAndRestore = "バックアップと復元",
    backupAndRestoreDescription = "設定JSONファイルのインポート/エクスポート",
    nextRequiredPermission = "次に必要な権限",
    permissionReadyMessage = "必要な権限はすべて許可されています。",
    usageAccessSettingsDestination = "Androidの使用状況へのアクセス設定でCraftPresenceを許可してください。",
    appNotificationSettingsDestination = "Androidのアプリ通知設定でCraftPresence通知を許可してください。",
    notificationAccessSettingsDestination = "Androidの通知アクセス設定でCraftPresenceを許可してください。",
    permissionReturnHint = "設定後、アプリに戻って権限状態を更新してください。",
    showForegroundApp = "前面アプリを表示",
    showForegroundAppDescription = "アプリ上部に現在開いているアプリ名とパッケージを表示します。",
    showForegroundAppNotification = "前面アプリ通知",
    showForegroundAppNotificationDescription = "現在の前面アプリをAndroid通知で表示し続けます。",
    notificationPermissionMissing = "通知権限がオフの場合は表示されません。",
    appNotificationPermission = "アプリ通知",
    appNotificationPermissionDescription = "現在の前面アプリを通知として表示するために必要です。",
    discordAutoConnectDescriptionOn = "次回起動からバックグラウンドでDiscord接続を試みます。",
    discordAutoConnectDescriptionOff = "次回起動時に初期接続ウィンドウを表示します。",
    resetElapsedTimeOnScheduledPresetRestore = "予約 Presence 復元時に経過時間をリセット",
    resetElapsedTimeOnScheduledPresetRestoreDescription = "予約プリセット終了後に以前の Presence を復元するとき、開始時刻を現在時刻に設定し直します。",
    language = "言語",
    registeredPackages = "登録済みパッケージ",
    customPresenceSettings = "個別Presence設定",
    settingsImportExport = "設定のインポート/エクスポート",
    settingsImportExportDescription = "登録アプリ、表示名、Presence設定をJSONファイルとして保存または復元します。",
    settingsExport = "エクスポート",
    settingsExportSuccess = "設定JSONファイルをエクスポートしました。",
    settingsExportOpenFailed = "エクスポート先のファイルを開けませんでした。",
    settingsImport = "インポート",
    settingsImportSuccess = "設定をインポートしました。",
    settingsImportOpenFailed = "インポートするファイルを開けませんでした。",
    settingsImportConfirmTitle = "設定をインポートしますか？",
    settingsImportConfirmMessage = "現在の設定はJSONファイルの設定に置き換えられます。",
    settingsTransferError = "設定ファイルを処理できませんでした。",
    settingsTransferResult = "設定ファイル",
    configured = "設定済み",
    authorizing = "認証中",
    connecting = "接続中",
    ready = "準備完了",
    unauthorized = "未認証",
    failed = "失敗",
    authorized = "認証済み",
    playingActivity = "プレイ中",
    streamingActivity = "配信中",
    listeningActivity = "視聴中",
    watchingActivity = "観戦中",
    competingActivity = "競争中",
    languageSystem = "システム",
    languageJapanese = "日本語",
)
